const popupData = [
    {
      title: '포트폴리오 사이트',
      sub: '2025.03 - 진행중 | 1인 프로젝트',
      tag1: '개인 프로젝트',
      tag2: '웹',
      tag3: '반응형',
      tag4: '포트폴리오',
      image: '/assets/images/image18.png',
      title2: '사용기술 및 언어',
      skill1: 'REACT',
      skill2: 'CSS',
      title3: '주요 기능',
      feature1: '개발자의 정보와 사용가능한 기술들을 확인할 수 있다.',
      feature1Img: '/assets/images/image19.png',
      feature2: '프로젝트 설명 및 GitHub 연결',
      feature2Img: '/assets/images/image20.png',
      feature3: '연락처 및 이메일 정보',
      feature3Img: '/assets/images/image46.png'
    },
    {
      title: '돈슐랭가이드',
      sub: '2025.01 - 2주 | 1인 프로젝트',
      tag1: '개인 프로젝트',
      tag2: '웹',
      tag3: '반응형',
      image: '/assets/images/image17.png',
      title2: '사용기술 및 언어',
      skill1: 'HTML',
      skill2: 'CSS',
      skill3: 'Java',
      skill4: 'Thymeleaf',
      skill5: 'JavaScript',
      title3: '주요 기능',
      feature1: '메인페이지(이미지 슬라이드)',
      feature1Img: '/assets/images/image21.gif',
      feature2: '돈까스랭킹(지역별)을 확인가능하다.',
      feature2Img: '/assets/images/image23.gif',
      feature3: '개발자의 돈까스에 대한 철학을 알 수 있다.',
      feature3Img: '/assets/images/image24.png',
      feature4: '사이트를 방문하는 사람들과 서로 맛집을 추천하거나 확인할 수 있다.',
      feature4Img: '/assets/images/image25.gif'
    },
    {
      title: 'Project_Planner',
      sub: '2024.08 - 한달 | 3인 프로젝트',
      tag1: '팀 프로젝트',
      tag2: '웹',
      image: '/assets/images/image16.png',
      title2: '사용기술 및 언어',
      skill1: 'HTML',
      skill2: 'CSS',
      skill3: 'Java',
      skill4: 'Thymeleaf',
      skill5: 'JavaScript',
      skill6: 'VUE.JS',
      title3: '주요 기능',
      feature1: '풀캘린더 (개인/팀/간트 일정조회)',
      feature1Img: '/assets/images/image26.gif',
      feature2: '풀캘린더 (일정 - 등록/수정/삭제)',
      feature2Img: '/assets/images/image27.gif',
      feature2_1Img: '/assets/images/image28.gif',
      feature3: '자유게시판(이름,작성자로 게시물검색)',
      feature3Img: '/assets/images/image30.gif',
      feature4: '자유게시판(게시글상세, 첨부파일 다운)',
      feature4Img: '/assets/images/image31.gif',
      feature5: '자유게시판(게시글등록, 수정, 삭제)',
      feature5Img: '/assets/images/image32.gif',
      feature5_1Img: '/assets/images/image33.gif',
      feature6: '메일전송',
      feature6Img: '/assets/images/image34.gif',
      feature7: '메일전송(사원메일조회)',
      feature7Img: '/assets/images/image35.gif',
      feature8: '메일전송(언어변경)',
      feature8Img: '/assets/images/image36.gif'
    },
    {
      title: '휴먼철도999',
      sub: '2024.07 - 2주 | 3인 프로젝트',
      tag1: '팀 프로젝트',
      tag2: '웹',
      image: '/assets/images/image37.png',
      title2: '사용기술 및 언어',
      skill1: 'HTML',
      skill2: 'CSS',
      skill3: 'Java',
      skill4: 'JavaScript',
      title3: '주요 기능',
      feature1: '메인페이지(이미지 슬라이드)',
      feature1Img: '/assets/images/image38.png',
      feature2: '메인페이지 - 열차조회',
      feature2Img: '/assets/images/image39.png',
      feature3: '메인페이지 - 추천여행지',
      feature3Img: '/assets/images/image40.png',
      feature4: '메인페이지 - 노선도',
      feature4Img: '/assets/images/image41.png',
      feature5: '마이페이지',
      feature5Img: '/assets/images/image42.png',
      feature6: '마이페이지 - 예약한 열차조회',
      feature6Img: '/assets/images/image43.png'
    }
  ];
  
  export default popupData;
  